descriptor-schema-version: "2.2"

info:
  name: JEA-FogLAMP-Docker-IOx
  description: "IOx Docker running FogLAMP with JEA plugins"
  version: "1.7.0"
  author-link: "https://raesemann.com"
  author-name: "Rob Raesemann"
app:
  cpuarch: "x86_64"
  type: docker
  env:
    FOGLAMP_ROOT: /usr/local/foglamp
  resources:
    profile: custom
    cpu: "6000"
    disk: "32768"
    memory: "1984"
    network:
      -
        interface-name: eth1
        ports: 
          tcp: [8081, 1995, 502, 23]
  startup:
    rootfs: rootfs.tar
    target: ["bash", "/usr/local/foglamp/foglamp.sh"]